# Generated by Django 6.0.1 on 2026-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_ai_generated_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
