# Generated by Django 6.0.1 on 2026-03-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_ats_feedback_resume_ats_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ai_generated_resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ats_feedback',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ats_score',
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_generated_resume', models.TextField(blank=True, null=True)),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('ats_feedback', models.TextField(blank=True, null=True)),
                ('pipeline_data', models.JSONField(blank=True, help_text='Stores the step-by-step LLM trace', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
        ),
    ]
