# Generated by Django 6.0.1 on 2026-03-21 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resume_ai_generated_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='target_job_description',
            new_name='ai_generated_resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='resumeversion',
            name='ai_generated_resume',
        ),
        migrations.RemoveField(
            model_name='resumeversion',
            name='ats_feedback',
        ),
        migrations.RemoveField(
            model_name='resumeversion',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='resumeversion',
            name='pipeline_data',
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='version_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
